TARGET_CPU 				:= cortex-m4
TARGET_ARCH 			:= armv7e-m
TARGET_FLOAT_HARDWARE 	:= hard
TARGET_FLOAT_FORMAT 	:= fpv4-sp-d16
TARGET_SYMBOL_BOARD 	:= __MSP432P401R__
TARGET_SYMBOL_FAMILY 	:= DeviceFamily_MSP432P401x
